# Project information
site_name: Mapping Docs
#site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Antonio Turley

# Repository
repo_name: MappingOurThoughts
repo_url: https://github.com/MappingOurThoughts

# Copyright
copyright: Copyright &copy; 2022 Mapping Our Thoughts

theme:
    name: material

    # Static files
    static_templates:
        - 404.html

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml
    language: en
    features:
        - announce.dismiss
        - content.code.annotate
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.indexes
        # - navigation.instant
        # - navigation.prune
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        # - toc.integrate
    palette:
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to system preference

    font: 
        text: Source Sans Pro 
        code: Source Sans Pro

    logo: assets/logo.png
    
    extra_css:
       - stylesheets/extra.css

# Navigation Tree
nav:
    - Mapping Our Thoughts: https://www.mappingourthoughts.org
    - Getting started: 
        - Zoom: started/zoom.md
        - Upload files: started/cloud.md
        - Customized Workstation: started/workstation.md
        - Encrypted email: started/email.md
        - Git and GitHub: started/git.md
        - Unix terminal: started/terminal.md
    - Beginning C/C++: 
        - Getting started: beginning/getting-started.md
    - Data structures C/C++:
        - Linked lists: data-structures/linked-lists.md 
    - Documentation: 
        - Resources: documentation/resources.md
    - Design principles: principles/principles.md
    - Coding standards: standards/standards.md
